# Generated by Django 5.2.1 on 2025-05-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_snippet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='public',
            field=models.CharField(choices=[('yes', 'Public'), ('no', 'Private')], max_length=30, null=True),
        ),
    ]
