# Generated by Django 5.2.1 on 2025-05-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_snippet_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='public',
            field=models.CharField(blank=True, choices=[('yes', 'Public'), ('no', 'Private')], max_length=30, null=True),
        ),
    ]
